version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: orpheo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orpheo_db
      POSTGRES_USER: orpheo_user
      POSTGRES_PASSWORD: orpheo_secure_2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orpheo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orpheo_user -d orpheo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: orpheo-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3001}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: orpheo_db
      DB_USERNAME: orpheo_user
      DB_PASSWORD: orpheo_secure_2025
      DATABASE_URL: postgresql://orpheo_user:orpheo_secure_2025@postgres:5432/orpheo_db
      JWT_SECRET: ${JWT_SECRET:-orpheo-jwt-secret-super-seguro-cambiar-en-produccion-2025}
      JWT_EXPIRY: ${JWT_EXPIRY:-1h}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-orpheo-refresh-token-secret-super-seguro-2025}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY:-30d}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      UPLOAD_PATH: ./uploads
      MAX_FILE_SIZE: 10485760
      SOCKET_CORS_ORIGIN: ${SOCKET_CORS_ORIGIN:-*}
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - orpheo-network

  # pgAdmin (opcional para administración)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: orpheo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@orpheo.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - orpheo-network
    profiles:
      - admin  # Solo se inicia con --profile admin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  orpheo-network:
    driver: bridge